name: jelly_blob
description: "A dynamic, animated blob effect package for Flutter widgets."
version: 1.0.2
homepage: https://github.com/suojae/jelly-blob
repository: https://github.com/suojae/jelly-blob
issue_tracker: https://github.com/suojae/jelly-blob/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  melos: ^6.3.2

flutter:

  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Schyler-Regular.ttf
        - asset: fonts/Schyler-Italic.ttf
          style: italic
